pub mod anchor;
pub mod decimal;
pub mod error;
pub mod function;
pub mod instruction;
pub mod queue;
pub mod quote;
pub mod sgx;
pub use anchor::*;
use anchor_lang::prelude::*;
pub use decimal::*;
pub use error::*;
pub use function::*;
pub use instruction::*;
pub use queue::*;
pub use quote::*;
pub use sgx::*;
use solana_sdk::pubkey;

pub const ATTESTATION_PID: Pubkey = pubkey!("2No5FVKPAAYqytpkEoq93tVh33fo4p6DgAnm4S6oZHo7");
